Add a retry logic for uploading stemcell and release

diff --git a/bosh-setup/scripts/setup_env b/bosh-setup/scripts/setup_env
--- a/bosh-setup/scripts/setup_env
+++ b/bosh-setup/scripts/setup_env
@@ -16,6 +16,10 @@ function retryop()
       sleep $interval
     fi
   done
+  if [ ${retry} -eq ${max_retries} ]; then
+    echo "Operation failed: $1"
+    exit 1
+  fi
 }
 
 echo "Start to update package lists from repositories..."
