Fix the timeout issue of "pip install" in China
1. Add --index-url and --default-timeout
2. Retry to install Python packages if failed

diff --git a/bosh-setup/scripts/setup_env b/bosh-setup/scripts/setup_env
--- a/bosh-setup/scripts/setup_env
+++ b/bosh-setup/scripts/setup_env
@@ -1,25 +1,29 @@
 #!/usr/bin/env bash
 
+function retryop()
+{
+  retry=0
+  max_retries=10
+  interval=30
+  while [ ${retry} -lt ${max_retries} ]; do
+    echo "Operation: $1, Retry #${retry}"
+    eval $1
+    if [ $? -eq 0 ]; then
+      echo "Successfully."
+      break
+    else
+      let retry=retry+1
+      sleep $interval
+    fi
+  done
+}
+
 echo "Start to update package lists from repositories..."
-n=0
-max=10
-interval=30
-until [ $n -ge $max ]
-do
-  apt-get update && break
-  n=$[$n+1]
-  echo "Failed to update package lists. Sleep $interval seconds and retry #$n ..."
-  sleep $interval
-done
-if [ $n -ge $max ]; then
-  echo "Failed to update package lists with retrying $max times"
-  exit 1
-fi
+retryop "apt-get update"
+
+retryop "apt-get -y install python-pip jq"
 
 set -e
-
-apt-get -y install python-pip jq
-pip install msrest msrestazure azure==2.0.0rc1 azure-storage netaddr
 
 seq_no=$(cat ../../mrseq)
 custom_script_config_file="../../config/${seq_no}.settings"
@@ -33,6 +37,24 @@ function get_setting() {
   local value=$(echo $settings | jq ".$key" -r)
   echo $value
 }
+
+environment=$(get_setting ENVIRONMENT)
+
+set +e
+
+echo "Start to install python packages..."
+pkg_list="msrest msrestazure azure==2.0.0rc1 azure-storage netaddr"
+if [ "$environment" = "AzureChinaCloud" ]; then
+  for pkg in $pkg_list; do
+    retryop "pip install $pkg --index-url https://pypi.mirrors.ustc.edu.cn/simple/ --default-timeout=60"
+  done
+else
+  for pkg in $pkg_list; do
+    retryop "pip install $pkg"
+  done
+fi
+
+set -e
 
 username=$(get_setting ADMIN_USER_NAME)
 home_dir="/home/$username"
@@ -69,7 +91,6 @@ cp single-vm-cf.yml $example_manifests
 cp multiple-vm-cf.yml $example_manifests
 
 cp cf* $home_dir
-environment=$(get_setting ENVIRONMENT)
 bosh_init_url=$(get_setting BOSH_INIT_URL)
 install_log="$home_dir/install.log"
 chmod +x init.sh
